# Generated by Django 4.2.7 on 2023-11-14 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ingredients', models.TextField(default='Ингридиенты не указаны')),
                ('method', models.TextField(default='Способ приготовления не указан')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook_api.category')),
            ],
        ),
    ]
